/* Hardware transports: ESP32 simulator, BLE UART, MIDI, WebSocket. */
"use strict";
window.MixerAdapters=(()=>{let active=null;const listeners=new Set();const emit=s=>{listeners.forEach(fn=>fn({...s}));window.MixerControl?.setStatus?.(s)};const onStatus=fn=>(listeners.add(fn),()=>listeners.delete(fn));
const NUS={service:"6e400001-b5a3-f393-e0a9-e50e24dcca9e",write:"6e400002-b5a3-f393-e0a9-e50e24dcca9e",notify:"6e400003-b5a3-f393-e0a9-e50e24dcca9e"};
function receive(obj){if(!obj)return;try{if(typeof obj==="string")obj=JSON.parse(obj)}catch{return}if(obj.type==="mixer-control"||obj.control)window.MixerControl?.applyRemote?.(obj);if(active?.type==="simulator"){active.rx.push(obj)}}
function encode(command){return JSON.stringify({type:"mixer-control",channel:command.channel,control:command.control,value:Number(command.value),time:Date.now()})+"\n"}
async function simulator(){if(active?.type==="simulator"&&active.connected)return active;if(active){disconnect()}active={type:"simulator",name:"ESP32 SIMULATOR",connected:true,tx:[],rx:[],state:{},startedAt:Date.now()};emit({connected:true,transport:"simulator",type:"simulator",name:active.name,deviceName:active.name,protocol:"ESP32-JSON",detail:"ESP32 virtual • TX/RX aktif"});return active}
async function bluetooth(){if(!navigator.bluetooth)throw Error("Web Bluetooth tidak didukung browser ini");const device=await navigator.bluetooth.requestDevice({filters:[{services:[NUS.service]}],optionalServices:[NUS.service]});const server=await device.gatt.connect();const service=await server.getPrimaryService(NUS.service);const write=await service.getCharacteristic(NUS.write);const notify=await service.getCharacteristic(NUS.notify);await notify.startNotifications();notify.addEventListener("characteristicvaluechanged",e=>{const text=new TextDecoder().decode(e.target.value);text.split(/\r?\n/).filter(Boolean).forEach(s=>receive(s))});active={type:"bluetooth",name:device.name||"ESP32",device,server,write,notify,connected:true};device.addEventListener("gattserverdisconnected",()=>{active=null;emit({connected:false,transport:"none",type:"none",name:"Terputus",deviceName:"Terputus",protocol:"none",detail:"ESP32 BLE terputus"})});emit({connected:true,transport:"bluetooth",type:"bluetooth",name:active.name,deviceName:active.name,protocol:"ESP32 BLE UART",detail:"BLE TX/RX aktif"});return active}
async function midi(){if(!navigator.requestMIDIAccess)throw Error("Web MIDI tidak didukung browser ini");const access=await navigator.requestMIDIAccess();const outputs=[...access.outputs.values()],inputs=[...access.inputs.values()];if(!outputs.length&&!inputs.length)throw Error("Perangkat MIDI tidak ditemukan");active={type:"midi",name:outputs[0]?.name||inputs[0]?.name||"MIDI",output:outputs[0]||null,input:inputs[0]||null,connected:true};if(active.input)active.input.onmidimessage=e=>window.MixerFeedback?.fromMidi?.([...e.data],active);emit({connected:true,transport:"midi",type:"midi",name:active.name,deviceName:active.name,protocol:"MIDI CC",detail:outputs.length+" output / "+inputs.length+" input"});return active}
async function network(url){if(!url)throw Error("Alamat WebSocket belum diisi");const ws=new WebSocket(url);await new Promise((res,rej)=>{ws.onopen=res;ws.onerror=()=>rej(Error("WebSocket gagal"))});ws.onmessage=e=>receive(e.data);active={type:"network",name:url,ws,connected:true};emit({connected:true,transport:"network",type:"network",name:url,deviceName:url,protocol:"JSON WebSocket",detail:"WebSocket TX/RX aktif"});return active}
async function usbAudio(){if(!navigator.mediaDevices?.getUserMedia)throw Error("Audio input tidak tersedia");const ds=await navigator.mediaDevices.enumerateDevices(),ins=ds.filter(d=>d.kind==="audioinput");if(!ins.length)throw Error("USB audio input tidak ditemukan");const stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:{exact:ins[0].deviceId},echoCancellation:false,noiseSuppression:false,autoGainControl:false}});active={type:"usb-audio",name:ins[0].label||"USB Audio",stream,connected:true};emit({connected:true,transport:"usb-audio",type:"usb-audio",name:active.name,deviceName:active.name,protocol:"Audio",detail:"USB audio input aktif"});return active}
function disconnect(){try{active?.ws?.close();active?.device?.gatt?.disconnect?.();active?.stream?.getTracks?.().forEach(t=>t.stop())}catch{}active=null;emit({connected:false,transport:"none",type:"none",name:"Belum terhubung",deviceName:"Belum terhubung",protocol:"none",detail:""})}
function value127(command,m){const lo=Number(m?.min??0),hi=Number(m?.max??1),v=Number(command.value);return hi<=lo?0:Math.max(0,Math.min(127,Math.round((v-lo)/(hi-lo)*127)))}
function sendMapped(command,maps){if(!active)return{ok:false,reason:"offline"};try{if(active.type==="simulator"){if(!active.connected)return{ok:false,reason:"simulator_offline"};const key=command.channel+":"+command.control;const value=Number(command.value);active.state[key]=Number.isFinite(value)?value:command.value;const tx={...command,direction:"TX",time:Date.now()};active.tx.push(tx);emit({connected:true,transport:"simulator",type:"simulator",name:active.name,deviceName:active.name,protocol:"ESP32-JSON",detail:"TX "+command.channel+" • "+command.control+" = "+command.value,lastTx:tx});return{ok:true,transport:"simulator",tx}}if(active.type==="bluetooth"){const bytes=new TextEncoder().encode(encode(command));return active.write.writeValue(bytes).then(()=>({ok:true,transport:"bluetooth"})).catch(e=>({ok:false,reason:e.message}))}if(active.type==="network"){active.ws.send(encode(command));return{ok:true,transport:"network"}}const m=maps?.[command.control];if(active.type==="midi"&&active.output&&m){let val=value127(command,m);if(command.control==="mute"||command.control==="solo")val=Number(command.value)>0?127:0;const ch=Math.max(0,Math.min(15,Number(m.channel)||0)),cc=Math.max(0,Math.min(127,Number(m.cc)||0));active.output.send([0xB0+ch,cc,val]);return{ok:true,transport:"midi"}}return{ok:false,reason:"unsupported"} }catch(e){return{ok:false,reason:e.message||"send failed"}}}
return{onStatus,simulator,bluetooth,midi,network,usbAudio,disconnect,sendMapped,receive,get active(){return active}}})();