function getConfiguredChannelCount(){const el=document.querySelector("#channelCount");const n=Number(el?.value);return Math.max(1,Math.min(64,Number.isFinite(n)&&n>0?n:(state.channels?.length||16)))}
function refreshHardwareTestTargets(){const box=document.querySelector(".hardware-test");const selects=box?.querySelectorAll("select");const targetSel=selects?.[0];if(!targetSel)return;const oldTarget=targetSel.value;const count=getConfiguredChannelCount();const controls=["FADER","GAIN","LOW","MID","HIGH","PAN","MUTE","SOLO"];targetSel.innerHTML="";for(let ch=1;ch<=count;ch++)for(const control of controls){const o=document.createElement("option");o.value=control+" CH"+ch;o.textContent=control+" CH"+ch;targetSel.appendChild(o)}targetSel.value=[...targetSel.options].some(o=>o.value===oldTarget)?oldTarget:(targetSel.options[0]?.value||"FADER CH1");let valueEl=box.querySelector(".hardware-test-value");if(!valueEl){valueEl=selects?.[1]||document.createElement("input");valueEl.classList.add("hardware-test-value");if(valueEl.tagName==="SELECT")valueEl.replaceWith(document.createElement("input"));valueEl=box.querySelector(".hardware-test-value");}const syncValue=()=>{const control=targetSel.value.split(/\s+CH/i)[0].toUpperCase();if(control==="MUTE"||control==="SOLO"){if(valueEl.tagName!=="SELECT"){const n=document.createElement("select");n.className="hardware-test-value";n.innerHTML="<option>ON</option><option>OFF</option>";valueEl.replaceWith(n);valueEl=n}}else{if(valueEl.tagName!=="INPUT"){const n=document.createElement("input");n.className="hardware-test-value";n.type="number";valueEl.replaceWith(n);valueEl=n}const cfg={FADER:[0,100,1,50,"%"],GAIN:[0,2,.01,1,""],LOW:[-12,12,.1,0," dB"],MID:[-12,12,.1,0," dB"],HIGH:[-12,12,.1,0," dB"],PAN:[-1,1,.01,0,""]}[control]||[0,100,1,0,""];valueEl.min=cfg[0];valueEl.max=cfg[1];valueEl.step=cfg[2];if(valueEl.value===""||valueEl.dataset.control!==control)valueEl.value=cfg[3];valueEl.dataset.control=control;valueEl.placeholder=control+" ("+cfg[0]+"…"+cfg[1]+")"} };targetSel.addEventListener("change",syncValue);syncValue();}
function bindReferenceControls(){
  const root=document.querySelector(".reference-panel"); if(!root)return;
  const lockedKey="mixer-online-live-lock";
  const lamp=b=>{if(!b)return;let l=b.querySelector(":scope > .control-lamp");if(!l){l=document.createElement("i");l.className="control-lamp off";b.prepend(l)}return l};
  const notify=(msg,on=true)=>{status(msg);document.dispatchEvent(new CustomEvent("mixer:notification",{detail:{message:msg,on}}))};
  const setOn=(b,on,label)=>{if(!b)return;b.classList.toggle("indicator-active",!!on);b.setAttribute("aria-pressed",on?"true":"false");const l=lamp(b);l?.classList.toggle("on",!!on);l?.classList.toggle("off",!on);b.dataset.on=on?"1":"0";if(label)b.dataset.statusLabel=label};
  const setLock=on=>{document.body.classList.toggle("mixer-locked",on);const b=root.querySelector(".lock-row button");if(b){b.textContent=on?"🔓 UNLOCK":"🔒 LOCK";setOn(b,on)}try{localStorage.setItem(lockedKey,on?"1":"0")}catch{}};
  let locked=false;try{locked=localStorage.getItem(lockedKey)==="1"}catch{}setLock(locked);

  // BUS/AUX level controls: real value, visible level, ON/OFF lamp.
  root.querySelectorAll(".bus-master label").forEach((label,i)=>{const x=label.querySelector("input[type=range]");if(!x)return;const key="mixer-bus-"+(i+1);const saved=Number(localStorage.getItem(key));if(Number.isFinite(saved))x.value=Math.max(0,Math.min(100,saved));const update=()=>{const v=Number(x.value);label.dataset.level=x.value;label.classList.toggle("active-level",v>0);const l=label.querySelector(".control-lamp");l?.classList.toggle("on",v>0);l?.classList.toggle("off",v<=0);try{localStorage.setItem(key,String(v))}catch{}if(!locked){send("BUS "+(i+1),"level",v);notify("BUS "+(i+1)+" "+(v>0?"ON":"OFF")+" • "+v+"% ",v>0)}};x.addEventListener("input",update);x.addEventListener("change",update);update();});

  // FX controls.
  ["fxDelay","fxFeedback","fxWet"].forEach(id=>root.querySelector("#"+id)?.addEventListener("input",e=>{const v=Number(e.target.value);if(!locked)send("FX 1",id.replace("fx","").toLowerCase(),v);notify("FX 1 "+(v>0?"ON":"OFF")+" • "+id.replace("fx","").toUpperCase()+" "+v)}));
  root.querySelector("#fxType")?.addEventListener("change",e=>{if(!locked)send("FX 1","type",e.target.value)});
  root.querySelector("#fxPreset")?.addEventListener("change",e=>{
    const presets={VOCAL:{type:"reverb",delay:25,feedback:18,wet:35},"MC / SPEECH":{type:"delay",delay:18,feedback:12,wet:22},MUSIC:{type:"delay",delay:30,feedback:28,wet:30},HALL:{type:"reverb",delay:55,feedback:35,wet:48},CUSTOM:null};
    const p=presets[e.target.value];if(!p||locked)return;
    const type=root.querySelector("#fxType");if(type)type.value=p.type;
    [["fxDelay",p.delay],["fxFeedback",p.feedback],["fxWet",p.wet]].forEach(([id,v])=>{const x=root.querySelector("#"+id);if(x){x.value=v;x.dispatchEvent(new Event("input",{bubbles:true}))}});
    notify("FX "+e.target.value+" ON");
  });

  // Output routing: selectable and visibly active.
  root.querySelectorAll(".routing-block select").forEach((sel,i)=>sel.addEventListener("change",()=>{if(locked)return;const on=sel.value!=="MAIN L/R";setOn(sel,on);send("OUT "+(i+1),"route",sel.value);notify("OUT "+(i+1)+" "+(on?"ON":"OFF")+" → "+sel.value)}));

  // Scenes.
  const input=root.querySelector(".scene-row input"),rows=[...root.querySelectorAll(".scene-row")],buttons=[...root.querySelectorAll(".scene-row button")];
  const sceneName=()=>input?.value?.trim()||"Scene";
  const sceneState=()=>({channels:state.channels.map(c=>({fader:Number(c.querySelector(".fader")?.value||0),muted:c.classList.contains("muted"),soloed:c.classList.contains("soloed")})),master:Number($("#masterFader")?.value||80),musicMode:$("#musicMode")?.value||"sequential",savedAt:Date.now()});
  const applyScene=o=>{if(!o)return;state.channels.forEach((ch,i)=>{const v=o.channels?.[i];if(!v)return;const f=ch.querySelector(".fader");if(f){f.value=v.fader;ch.querySelector(".value")&&(ch.querySelector(".value").textContent=Math.round(v.fader)+"%")}ch.classList.toggle("muted",!!v.muted);ch.classList.toggle("soloed",!!v.soloed);ch.querySelectorAll(".mute,.topmute").forEach(b=>b.textContent=v.muted?"UNMUTE":"MUTE");updateChannelAudio(ch)});if($("#masterFader")&&o.master!=null){$("#masterFader").value=o.master;$("#masterValue")&&($("#masterValue").textContent=o.master+"%");$("#masterFader").dispatchEvent(new Event("input",{bubbles:true}))};notify("SCENE RECALLED")};
  const findBtn=t=>buttons.find(b=>b.textContent.trim()===t);
  findBtn("SAVE")?.addEventListener("click",()=>{try{localStorage.setItem("mixer-scene-"+sceneName(),JSON.stringify(sceneState()));notify("SCENE SAVED • "+sceneName());setOn(findBtn("SAVE"),true)}catch{notify("SCENE SAVE ERROR",false)}});
  findBtn("RECALL")?.addEventListener("click",()=>{try{applyScene(JSON.parse(localStorage.getItem("mixer-scene-"+sceneName())||"null"))}catch{notify("SCENE NOT FOUND",false)}});
  findBtn("RENAME")?.addEventListener("click",()=>{if(input){input.focus();input.select()}notify("ENTER NEW SCENE NAME")});
  findBtn("DUPLICATE")?.addEventListener("click",()=>{try{const src=localStorage.getItem("mixer-scene-"+sceneName());if(!src){notify("SCENE NOT FOUND",false);return}const n=sceneName()+" COPY";localStorage.setItem("mixer-scene-"+n,src);if(input)input.value=n;notify("SCENE DUPLICATED")}catch{}});
  findBtn("DELETE")?.addEventListener("click",()=>{try{localStorage.removeItem("mixer-scene-"+sceneName());notify("SCENE DELETED");setOn(findBtn("DELETE"),true)}catch{}});
  findBtn("EXPORT")?.addEventListener("click",()=>{const blob=new Blob([JSON.stringify(sceneState(),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=sceneName()+".json";a.click();URL.revokeObjectURL(a.href);notify("SCENE EXPORTED")});
  const importInput=document.createElement("input");importInput.type="file";importInput.accept=".json,application/json";importInput.hidden=true;root.appendChild(importInput);
  findBtn("IMPORT")?.addEventListener("click",()=>importInput.click());importInput.addEventListener("change",async()=>{const file=importInput.files?.[0];if(!file)return;try{applyScene(JSON.parse(await file.text()));notify("SCENE IMPORTED")}catch{notify("IMPORT ERROR",false)}importInput.value=""});
  findBtn("↶ UNDO")?.addEventListener("click",()=>{document.execCommand("undo");notify("UNDO ON");setOn(findBtn("↶ UNDO"),true);setTimeout(()=>setOn(findBtn("↶ UNDO"),false),300)});
  findBtn("↷ REDO")?.addEventListener("click",()=>{document.execCommand("redo");notify("REDO ON");setOn(findBtn("↷ REDO"),true);setTimeout(()=>setOn(findBtn("↷ REDO"),false),300)});

  // Lock.
  root.querySelector(".lock-row button")?.addEventListener("click",()=>{locked=!locked;setLock(locked)});

  // Device / hardware.
  root.querySelector("#deviceConnect")?.addEventListener("click",async()=>{if(locked)return;const b=root.querySelector("#deviceConnect");const on=b?.classList.contains("indicator-active");if(on){window.MixerAdapters?.disconnect?.();setOn(b,false);notify("ESP32 OFF");return}try{const adapter=window.MixerAdapters?.simulator;if(typeof adapter!=="function")throw Error("ESP32 ADAPTER UNAVAILABLE");await adapter();setOn(b,true);notify("ESP32 ON • CONNECTED")}catch(e){setOn(b,false);notify("ESP32 OFF • "+(e.message||"UNAVAILABLE"),false)}});
  root.querySelector("#deviceDisconnect")?.addEventListener("click",()=>{const b=root.querySelector("#deviceDisconnect");const on=b?.classList.contains("indicator-active");if(on){window.MixerAdapters?.disconnect?.();setOn(b,false);notify("ESP32 DISCONNECT OFF",false)}else{window.MixerAdapters?.disconnect?.();setOn(root.querySelector("#deviceConnect"),false);setOn(b,true);notify("DISCONNECT ON",false)}});
  root.querySelector("#restartSimulator")?.addEventListener("click",async()=>{if(locked)return;const b=root.querySelector("#restartSimulator");const a=window.MixerAdapters;const isOn=a?.active?.type==="simulator"&&a.active?.connected===true;if(isOn){a.disconnect?.();setOn(b,false);const st=root.querySelector("#simulatorStatus");if(st)st.textContent="● OFFLINE";const detail=root.querySelector("#simulatorDetail");if(detail)detail.textContent="ESP32 virtual • simulator stopped";notify("ESP32 SIMULATOR OFF",false);return}setOn(b,false);notify("ESP32 SIMULATOR STARTING",false);try{if(typeof a?.simulator!=="function")throw Error("SIMULATOR UNAVAILABLE");const active=await a.simulator();const ok=active?.type==="simulator"&&active?.connected===true;setOn(b,ok);const st=root.querySelector("#simulatorStatus");if(st)st.textContent=ok?"● ONLINE":"● OFFLINE";const detail=root.querySelector("#simulatorDetail");if(detail)detail.textContent=ok?"ESP32 virtual • BLE/JSON ready • TX/RX synchronized":"ESP32 virtual • simulator stopped";notify(ok?"ESP32 SIMULATOR ON • TX/RX READY":"ESP32 SIMULATOR OFF",ok)}catch(e){setOn(b,false);const st=root.querySelector("#simulatorStatus");if(st)st.textContent="● OFFLINE";notify("ESP32 SIMULATOR OFF • "+(e.message||"ERROR"),false)}});

  root.querySelector(".mapper-row button:nth-of-type(1)")?.addEventListener("click",()=>{const n=Number(root.querySelector('.mapper-row input[type=number]')?.value||16);buildChannels(n);notify("CHANNELS APPLIED: "+n)});
  root.querySelector(".mapper-row button:nth-of-type(2)")?.addEventListener("click",()=>{state.channels.forEach((ch,i)=>{ch.dataset.mapped="1";ch.querySelectorAll("input,select").forEach(x=>x.dataset.autoMapped="1")});notify("CONTROLS AUTO MAPPED");setOn(root.querySelector(".mapper-row button:nth-of-type(2)"),true)});

  refreshHardwareTestTargets();

  root.querySelector(".hardware-test button")?.addEventListener("click",async()=>{if(locked)return;const box=root.querySelector(".hardware-test");const selects=box?.querySelectorAll("select");const target=String(selects?.[0]?.value||"FADER CH1");const control=target.split(/\s+CH/i)[0].trim().toLowerCase().replace(/\s+/g,"_");const m=target.match(/\s+CH\s*(\d+)/i);const ch=Number(m?.[1]||1);const valueEl=box?.querySelector(".hardware-test-value")||selects?.[1];let value;if(control==="mute"||control==="solo")value=String(valueEl?.value||"ON").toUpperCase()==="ON"?1:0;else value=Number(valueEl?.value);const limits={fader:[0,100],gain:[0,2],low:[-12,12],mid:[-12,12],high:[-12,12],pan:[-1,1]}[control];if(!Number.isFinite(value)||(limits&&(value<limits[0]||value>limits[1]))){notify("HARDWARE TEST INVALID VALUE • CH "+ch+" "+control.toUpperCase(),false);return}const button=box?.querySelector("button");try{const adapter=window.MixerAdapters?.active;if(!adapter?.connected&&window.MixerAdapters?.simulator)await window.MixerAdapters.simulator();const result=await window.MixerControl?.setControl?.("CH "+ch,control,value);if(result?.ok===false)throw Error(result.reason||"TX FAILED");const applied=applyHardwareTestToChannel(ch,control,value);setOn(button,control==="mute"||control==="solo"?value===1:true);notify("HARDWARE TEST • CH "+ch+" "+control.toUpperCase()+" = "+value+(applied?" • CHANNEL SYNC":" • TX OK"),control==="mute"||control==="solo"?value===1:true)}catch(e){setOn(button,false);notify("HARDWARE TEST FAILED • "+(e.message||"TX ERROR"),false)}});

  // Add a lamp to every actionable control in this panel only.
  root.querySelectorAll("button").forEach(b=>{if(!b.querySelector(".control-lamp")&&!b.closest(".lock-row")?.querySelector(".control-lamp"))lamp(b)});
  root.querySelectorAll(".device-online").forEach(x=>{if(!x.querySelector(".control-lamp")){const l=document.createElement("i");l.className="control-lamp on";x.prepend(l)}});
  root.querySelectorAll(".bus-master label").forEach(label=>{if(!label.querySelector(".control-lamp")){const l=document.createElement("i");l.className="control-lamp off";label.prepend(l)}});
  root.querySelectorAll(".bus-master input").forEach(x=>x.addEventListener("input",()=>{const l=x.parentElement.querySelector(".control-lamp");l?.classList.toggle("on",Number(x.value)>0);l?.classList.toggle("off",Number(x.value)<=0)}));
}

function initSystemNotifications(){if(window.__mixerNotifyBound)return;window.__mixerNotifyBound=true;const show=(msg,on=true)=>{let n=document.querySelector("#mixerNotification");if(!n){n=document.createElement("div");n.id="mixerNotification";n.setAttribute("role","status");n.setAttribute("aria-live","assertive");document.body.appendChild(n)}n.textContent=String(msg);n.dataset.state=on?"ON":"OFF";n.classList.toggle("is-on",on);n.classList.toggle("is-off",!on);n.classList.add("show");clearTimeout(window.__mixerNoticeTimer);window.__mixerNoticeTimer=setTimeout(()=>n.classList.remove("show"),2600)};window.mixerNotify=show;document.addEventListener("mixer:notification",e=>{const d=e.detail||{};show(d.message,d.on!==false)});}
function init(){initSystemNotifications();const count=Number($("#channelCount")?.value||16);buildChannels(count);refreshHardwareTestTargets();bindMusic();bindNativeButtons();bindTabs();bindConnection();bindMasterControls();bindReferenceControls();initIndicatorLights();bindMaifDcaUsbAudio();bindDcaControls();bindOnOffLamps();requestAnimationFrame(()=>{const box=$("#channels");box?.scrollTo?.({left:0,behavior:"auto"});initIndicatorLights();bindDcaControls();bindOnOffLamps();updateMeters()});$("#applyChannels")?.addEventListener("click",()=>{buildChannels($("#channelCount")?.value);refreshHardwareTestTargets();initIndicatorLights();bindDcaControls();bindOnOffLamps()});window.MixerAdapters?.simulator?.();drawSpectrum();setInterval(()=>{updateMeters();updateDcaValues()},60)}

/* Mixer Online core: one audio engine + one control engine. */
"use strict";
const AudioCtx=window.AudioContext||window.webkitAudioContext,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={channels:[],channelCount:16,solo:new Set(),audio:null,source:null,ctx:null,mixBus:null,masterGain:null,playlist:[],index:0,playing:false,urls:[],usbStream:null,usbSource:null,dcaSolo:new Set(),dcaGroups:new Set(),muteGroups:new Set(),activeRoute:"MAIN L/R"};window.__mixerState=state;window.MixerOnline={state};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0)),setText=(s,t)=>{const e=$(s);if(e)e.textContent=t};
const time=s=>Number.isFinite(s)?String(Math.floor(Math.max(0,s)/60)).padStart(2,"0")+":"+String(Math.floor(Math.max(0,s)%60)).padStart(2,"0"):"00:00";
function status(s){setText("#playerState",s);setText("#usbState",s)}
function ensureAudio(){if(state.audio)return;state.audio=new Audio();state.audio.preload="metadata";state.audio.crossOrigin="anonymous";state.audio.addEventListener("timeupdate",updatePlaybackUI);state.audio.addEventListener("loadedmetadata",updatePlaybackUI);state.audio.addEventListener("play",()=>{state.playing=true;status("PLAYING")});state.audio.addEventListener("pause",()=>{state.playing=false});state.audio.addEventListener("ended",()=>nextTrack(true));if(AudioCtx){state.ctx=new AudioCtx();state.source=state.ctx.createMediaElementSource(state.audio);state.mixBus=state.ctx.createGain();state.masterGain=state.ctx.createGain();state.masterAnalyser=state.ctx.createAnalyser();state.masterAnalyser.fftSize=256;state.masterAnalyser.smoothingTimeConstant=.72;state.source.connect(state.mixBus);state.mixBus.connect(state.masterGain);state.masterGain.connect(state.masterAnalyser);state.masterAnalyser.connect(state.ctx.destination)}}
async function wake(){if(state.ctx&&state.ctx.state!=="running")await state.ctx.resume()}
function updatePlaybackUI(){if(!state.audio)return;setText("#musicCurrent",time(state.audio.currentTime));setText("#musicDuration",time(state.audio.duration));setText("#screenTime",time(state.audio.currentTime)+" / "+time(state.audio.duration));setText("#musicNowPlaying",state.playlist[state.index]?.name||"Belum ada musik dipilih");const p=$("#musicProgress");if(p)p.style.width=(state.audio.duration?100*state.audio.currentTime/state.audio.duration:0)+"%";setText("#playerName",state.playlist[state.index]?.name||"NO SIGNAL")}
function renderPlaylist(){const q=$("#playlist");if(!q)return;q.innerHTML=state.playlist.length?state.playlist.map((f,i)=>`<button class="playlist-item ${i===state.index?"active":""}" data-i="${i}">${i+1}. ${f.name}</button>`).join(""):"Playlist kosong";$$(".playlist-item").forEach(b=>b.onclick=()=>loadTrack(Number(b.dataset.i),true))}
async function loadTrack(i=0,auto=false){if(!state.playlist.length)return;ensureAudio();const next=(i+state.playlist.length)%state.playlist.length;state.audio.pause();const oldIndex=state.index;const old=state.urls[oldIndex];if(old&&oldIndex!==next)try{URL.revokeObjectURL(old)}catch{}state.index=next;const url=URL.createObjectURL(state.playlist[state.index]);state.urls[state.index]=url;state.audio.src=url;state.audio.load();renderPlaylist();updatePlaybackUI();routeMusicChannel();status("READY");if(auto)await playMusic()}
async function playMusic(){if(!state.playlist.length){status("PILIH MUSIK");return false}ensureAudio();try{await wake();routeMusicChannel();await state.audio.play();state.playing=true;return true}catch(e){state.playing=false;status("GAGAL MEMUTAR");return false}}
function pauseMusic(){state.audio?.pause();state.playing=false;status("PAUSED")}
function nextTrack(auto=state.playing){if(!state.playlist.length)return;const mode=$("#musicMode")?.value||"sequential";let n=state.index;if(mode==="random"&&state.playlist.length>1)while(n===state.index)n=Math.floor(Math.random()*state.playlist.length);else n=(state.index+1)%state.playlist.length;loadTrack(n,auto)}
function prevTrack(){if(!state.playlist.length)return;loadTrack((state.index-1+state.playlist.length)%state.playlist.length,state.playing)}
function setPlaylist(files){state.playlist=[...files].filter(f=>f.type.startsWith("audio/")||/\.(mp3|wav|m4a|aac|ogg|flac)$/i.test(f.name));state.urls.forEach(u=>{try{URL.revokeObjectURL(u)}catch{}});state.urls=[];state.index=0;state.playing=false;renderPlaylist();if(state.playlist.length)loadTrack(0,false);else status("PILIH MUSIK")}
function bindMusic(){const input=$("#musicFile");input?.addEventListener("change",e=>setPlaylist(e.target.files));$("#pickMusic")?.addEventListener("click",()=>input?.click());$("#play")?.addEventListener("click",()=>state.audio&&!state.audio.paused?pauseMusic():playMusic());$("#prev")?.addEventListener("click",prevTrack);$("#next")?.addEventListener("click",()=>nextTrack(true));$("#stopMusic")?.addEventListener("click",()=>{state.audio?.pause();if(state.audio)state.audio.currentTime=0;state.playing=false;status("STOPPED")});const vol=$("#masterVol");vol?.addEventListener("input",()=>{const v=Number(vol.value);if(state.masterGain)state.masterGain.gain.value=v;else if(state.audio)state.audio.volume=v;setText("#musicVolumeValue",Math.round(v*100)+"%")});$("#audioPlayMode")?.addEventListener("change",e=>{const m=$("#musicMode");if(m)m.value=e.target.value==="ACAK"?"random":"sequential"});$("#musicMode")?.addEventListener("change",e=>{const m=$("#audioPlayMode");if(m)m.value=e.target.value==="random"?"ACAK":"BERURUTAN"});$("#musicChannel")?.addEventListener("change",routeMusicChannel)}
function routeMusicChannel(){if(!state.ctx||!state.mixBus)return;try{state.mixBus.disconnect()}catch(e){}state.channels.forEach(c=>{if(c._gain){try{c._gain.disconnect()}catch(e){}}});const target=Number(String($("#musicChannel")?.value||"CH 1").replace(/\D/g,""))||1;state.channels.forEach(c=>{const g=state.ctx.createGain(),a=state.ctx.createAnalyser();a.fftSize=256;a.smoothingTimeConstant=.72;c._gain=g;c._audio={analyser:a};g.connect(a);a.connect(state.masterGain);updateChannelAudio(c)});const c=state.channels[target-1];if(c&&c._gain)state.mixBus.connect(c._gain);updateMeters()}
function applyHardwareTestToChannel(ch,control,value){const c=state.channels?.[Number(ch)-1];if(!c)return false;const v=Number(value)>0;if(control==="mute"||control==="solo"){const cls=control==="mute"?"muted":"soloed";const btn=c.querySelector(control==="mute"?".mute":".solo");if(!btn)return false;if(c.classList.contains(cls)!==v)btn.click();else{if(control==="mute")c.querySelectorAll(".mute,.topmute").forEach(b=>b.textContent=v?"UNMUTE":"MUTE");if(control==="solo"){if(v)state.solo.add(Number(ch));else state.solo.delete(Number(ch));state.channels.forEach(updateChannelAudio)}}return true}if(control==="fader"){const input=c.querySelector(".fader");if(!input)return false;input.value=Math.round(Number(value));input.dispatchEvent(new Event("input",{bubbles:true}));return true}if(control==="gain"||control==="pan"){const knob=c.querySelector(control==="gain"?".gainKnob":".panKnob");if(!knob)return false;const v=Number(value);knob.dataset.value=String(v);const max=control==="gain"?2:1;const min=control==="gain"?0:-1;const norm=(v-min)/(max-min);knob.style.setProperty("--rot",(-135+norm*270)+"deg");updateChannelAudio(c);return true}if(control==="low"||control==="mid"||control==="high"){c.dataset[control]=String(Number(value));return true}return false}

function send(channel,control,value){return window.MixerControl?.setControl?.(channel==="MASTER"?"MASTER":"CH "+channel,control,value)}
function updateChannelAudio(c){const f=Number(c.querySelector(".fader")?.value||0)/100,g=Number(c.querySelector(".gainKnob")?.dataset.value||1)/2,muted=c.classList.contains("muted"),soloed=c.classList.contains("soloed"),hasSolo=state.solo.size>0;const level=(muted||(hasSolo&&!soloed))?0:f*g;if(c._gain)c._gain.gain.value=level}
function knobDrag(e,c,type){e.preventDefault();const k=e.currentTarget,startY=e.clientY,start=Number(k.dataset.value??(type==="gain"?1:0));k.setPointerCapture?.(e.pointerId);const move=ev=>{const d=(startY-ev.clientY)/90,v=type==="gain"?clamp(start+d,0,2):clamp(start+d,-1,1);k.dataset.value=v;k.style.setProperty("--rot",(-135+(type==="gain"?v/2:(v+1)/2)*270)+"deg");send(Number(c.dataset.channel),type,v);updateChannelAudio(c)};const up=()=>{removeEventListener("pointermove",move);removeEventListener("pointerup",up)};addEventListener("pointermove",move);addEventListener("pointerup",up);move(e)}
function buildChannel(n){const c=document.createElement("article");c.className="channel";c.dataset.channel=n;const initial=n===1?80:0;c.innerHTML=`<div class="ch-head"><span>CH ${n}</span><i></i></div><button class="ch-btn topmute">MUTE</button><button class="ch-btn solo">SOLO</button><output class="value">${initial}%</output><div class="knobs"><div><div class="knob gainKnob" data-value="1"></div><small>GAIN</small></div><div><div class="knob panKnob" data-value="0"></div><small>PAN</small></div></div><div class="fader-wrap"><div class="scale-y"><span>10</span><span>5</span><span>0</span><span>-5</span><span>-10</span><span>-20</span><span>-30</span><span>-40</span><span>-60</span><span>-∞</span></div><input class="fader ch-fader" type="range" min="0" max="100" value="${initial}"><div class="ch-lamp"></div></div><div class="ch-bottom"><button class="ch-btn mute">MUTE</button><div class="label">CH ${n}</div><div class="status">${n===1?"LIVE":"READY"}</div></div>`;const f=c.querySelector(".fader");f.addEventListener("input",()=>{c.querySelector(".value").textContent=Math.round(f.value)+"%";updateChannelAudio(c);send(n,"fader",Number(f.value));updateMeters()});c.querySelector(".gainKnob").addEventListener("pointerdown",e=>knobDrag(e,c,"gain"));c.querySelector(".panKnob").addEventListener("pointerdown",e=>knobDrag(e,c,"pan"));c.querySelectorAll(".mute,.topmute").forEach(b=>b.addEventListener("click",()=>{const on=!c.classList.contains("muted");c.classList.toggle("muted",on);c.querySelectorAll(".mute,.topmute").forEach(x=>x.textContent=on?"UNMUTE":"MUTE");updateChannelAudio(c);send(n,"mute",on?1:0)}));c.querySelector(".solo").addEventListener("click",()=>{const on=!c.classList.contains("soloed");c.classList.toggle("soloed",on);if(on)state.solo.add(n);else state.solo.delete(n);state.channels.forEach(updateChannelAudio);send(n,"solo",on?1:0)});state.channels.push(c);return c}
function buildChannels(n=16){n=Math.max(1,Math.min(64,Number(n)||16));state.channelCount=n;const box=$("#channels");if(!box)return;const existing=[...box.querySelectorAll(".channel")];if(existing.length===n&&state.channels.length===n){if(state.ctx)routeMusicChannel();updateMeters();refreshHardwareTestTargets();return}state.channels=[];box.replaceChildren();for(let i=1;i<=n;i++)box.appendChild(buildChannel(i));if(state.ctx)routeMusicChannel();updateMeters()}
function bindMaster(){/* master binding handled by bindMasterControls to avoid duplicate listeners */}
function bindConnection(){const b=$("#connectBtn");const setConn=(on,s)=>{if(b){b.classList.toggle("indicator-active",!!on);b.setAttribute("aria-pressed",on?"true":"false");const dot=b.querySelector(".dot");dot?.classList.toggle("offline",!on)}setText("#usbState",on?(s?.protocol||"ESP32-JSON"):"READY")};b?.addEventListener("click",async()=>{try{await wake();const a=window.MixerAdapters;if(!a)throw Error("ESP32 ADAPTER UNAVAILABLE");if(a.active?.type==="simulator"){a.disconnect();setConn(false);notify("ESP32 OFF",false);return}await a.simulator();setConn(true,a.active);notify("ESP32 ON • SIMULATOR CONNECTED",true)}catch(e){setConn(false);notify("ESP32 OFF • "+(e.message||"UNAVAILABLE"),false)}});$("#stopBtn")?.addEventListener("click",()=>{state.audio?.pause();if(state.audio)state.audio.currentTime=0;state.playing=false;status("STOPPED")});window.MixerAdapters?.onStatus?.(s=>{setConn(!!s.connected,s);const d=document.querySelector("#deviceConnect");if(d){d.classList.toggle("indicator-active",!!s.connected);d.setAttribute("aria-pressed",s.connected?"true":"false");const l=d.querySelector(".control-lamp");l?.classList.toggle("on",!!s.connected);l?.classList.toggle("off",!s.connected)}if(s.type==="simulator"||s.transport==="simulator"||s.type==="none"){const b=document.querySelector("#restartSimulator");b?.classList.toggle("indicator-active",!!s.connected&&s.type==="simulator");const st=document.querySelector("#simulatorStatus");if(st)st.textContent=(s.connected&&s.type==="simulator")?"● ONLINE":"● OFFLINE";const detail=document.querySelector("#simulatorDetail");if(detail)detail.textContent=(s.connected&&s.type==="simulator")?"ESP32 virtual • BLE/JSON ready • TX/RX synchronized":"ESP32 virtual • simulator stopped"}})}
function updateMeters(){const read=a=>{if(!a)return{r:0,p:0};try{const t=new Float32Array(a.fftSize||256);a.getFloatTimeDomainData(t);let sum=0,p=0;for(const v of t){sum+=v*v;p=Math.max(p,Math.abs(v))}return{r:Math.min(1,Math.sqrt(sum/t.length)*2.8),p:Math.min(1,p)}}catch{return{r:0,p:0}}};const master=read(state.masterAnalyser);const active=!!(state.audio&&!state.audio.paused);const fallback=active?.04:0;const mr=Math.max(master.r,fallback),mp=Math.max(master.p,active?.04:0);const set=(e,v)=>{if(e)e.style.height=Math.max(2,Math.min(100,v*100))+"%"};set($("#inL"),mr);set($("#inR"),Math.max(mr,master.r*.96));const input=$(".input-meter");input?.classList.toggle("signal-active",mr>.008);input?.classList.toggle("clip-active",mp>.98);const leds=input?.querySelectorAll(".input-leds .lamp");if(leds){leds[0]?.classList.toggle("active",mr>.008);leds[1]?.classList.toggle("active",mr>.008)}state.channels.forEach((c,i)=>{const z=read(c._audio?.analyser);const f=Number(c.querySelector(".fader")?.value||0)/100;const muted=c.classList.contains("muted"),soloed=c.classList.contains("soloed"),hasSolo=state.solo.size>0;const audible=!muted&&(!hasSolo||soloed);const r=audible?z.r:0,p=audible?z.p:0;const visual=Math.max(r,active&&audible?f*.035:0);const bar=c.querySelector(".ch-lamp");if(bar){bar.style.height=Math.max(2,Math.min(100,visual*100))+"%";bar.classList.toggle("signal",r>.008);bar.classList.toggle("peak",p>.82);bar.classList.toggle("clip",p>.98);bar.classList.toggle("off",!audible)}const head=c.querySelector(".ch-head i");head?.classList.toggle("signal",r>.008);head?.classList.toggle("peak",p>.82);head?.classList.toggle("clip",p>.98);head?.classList.toggle("off",!audible);c.classList.toggle("signal-active",r>.008);c.classList.toggle("peak-active",p>.82);const status=c.querySelector(".status");if(status)status.textContent=muted?"MUTED":(r>.008?"LIVE":(soloed?"SOLO":"READY"))});const ml=$(".master-strip")?.querySelectorAll(".lamps .lamp");if(ml){const n=ml.length;ml.forEach((x,j)=>{const threshold=(j+1)/(n+1);x.classList.toggle("active",mr>threshold*.72);x.classList.toggle("peak",mp>.82&&j>=n-2);x.classList.toggle("clip",mp>.98&&j===n-1)})}}
function drawSpectrum(){const cv=$("#specCanvas");if(!cv)return;const x=cv.getContext("2d");let t=0;const resize=()=>{const d=window.devicePixelRatio||1;cv.width=Math.max(1,cv.clientWidth*d);cv.height=Math.max(1,cv.clientHeight*d);x.setTransform(d,0,0,d,0,0)};window.addEventListener("resize",resize);resize();const frame=()=>{t+=.035;x.clearRect(0,0,cv.clientWidth,cv.clientHeight);for(let i=0;i<cv.clientWidth;i+=5){const h=8+Math.abs(Math.sin(i*.025+t))*38+Math.abs(Math.sin(i*.061-t))*28;x.fillStyle="#0878c9";x.fillRect(i,cv.clientHeight-h,3,h)}requestAnimationFrame(frame)};frame()}
function bindTabs(){const tabs=$$(".tabs button[data-tab]");const views={home:"#homeView",meters:"#metersView",eq:"#eqView",effect:"#effectView",routing:"#routingView",setup:"#setupView"};tabs.forEach(b=>b.addEventListener("click",()=>{tabs.forEach(x=>x.classList.toggle("active",x===b));Object.entries(views).forEach(([k,s])=>{const v=$(s);if(v)v.style.display=k===b.dataset.tab?"block":"none"});}));Object.entries(views).forEach(([k,s])=>{const v=$(s);if(v)v.style.display=k==="home"?"block":"none"})}
function bindMasterControls(){const m=$("#masterFader"),mute=$("#masterMute");m?.addEventListener("input",()=>{const v=Number(m.value);const o=$("#masterValue");if(o)o.textContent=v+"%";if(state.masterGain)state.masterGain.gain.value=v/100;send("MASTER","fader",v);updateMeters()});mute?.addEventListener("click",()=>{const on=!mute.classList.contains("active");mute.classList.toggle("active",on);mute.textContent=on?"UNMUTE":"MUTE";if(state.masterGain)state.masterGain.gain.value=on?0:Number(m?.value||80)/100;send("MASTER","mute",on?1:0)})}
function bindDcaControls(){const root=document.querySelector(".dca");if(!root)return;const setLamp=(b,on)=>{b.classList.toggle("indicator-active",on);const l=b.querySelector(".control-lamp");if(l){l.classList.toggle("on",on);l.classList.toggle("off",!on)}};root.querySelectorAll(".auto-option").forEach(b=>{if(b.dataset.bound)return;b.dataset.bound="1";b.addEventListener("click",()=>{const on=!b.classList.contains("indicator-active");setLamp(b,on);send(b.id,"active",on?1:0);status(b.querySelector("span")?.textContent+" "+(on?"ON":"OFF"))})});root.querySelectorAll(".dca-btn").forEach(b=>{if(b.dataset.dcaBound)return;b.dataset.dcaBound="1";const o=b.querySelector("output");if(o&&!o.value)o.value="0.0";b.addEventListener("click",()=>{const n=Number(b.dataset.dca);const on=!state.dcaSolo.has(n);on?state.dcaSolo.add(n):state.dcaSolo.delete(n);setLamp(b,on);if(o)o.value="0.0";send("DCA "+n,"solo",on?1:0);updateDcaValues();status("DCA "+n+" SOLO "+(on?"ON":"OFF"))})});root.querySelectorAll(".mute-groups button").forEach(b=>{if(b.dataset.muteGroupBound)return;b.dataset.muteGroupBound="1";b.addEventListener("click",()=>{const n=Number(b.dataset.group);const on=!state.muteGroups.has(n);on?state.muteGroups.add(n):state.muteGroups.delete(n);setLamp(b,on);const start=(n-1)*4+1;state.channels.filter(c=>{const ch=Number(c.dataset.channel);return ch>=start&&ch<start+4}).forEach(ch=>{ch.classList.toggle("group-muted",on);ch.classList.toggle("muted",on);updateChannelAudio(ch)});send("MUTE GROUP "+n,"mute",on?1:0);updateMeters();status("MUTE GROUP "+n+" "+(on?"ON":"OFF"))})});root.querySelectorAll(".dca-groups button").forEach(b=>{if(b.dataset.dcaGroupBound)return;b.dataset.dcaGroupBound="1";b.addEventListener("click",()=>{const n=Number(b.dataset.dcagroup);const on=!state.dcaGroups.has(n);on?state.dcaGroups.add(n):state.dcaGroups.delete(n);setLamp(b,on);send("DCA GROUP "+n,"active",on?1:0);status("DCA GROUP "+n+" "+(on?"ON":"OFF"))})});}
function bindOnOffLamps(){document.querySelectorAll(".dca-btn,.route-btn,.usb-route-btn,.mute-groups button,.dca-groups button,.groups button,.auto-check").forEach(b=>{if(b.dataset.lampBound)return;b.dataset.lampBound="1";const lamp=document.createElement("i");lamp.className="control-lamp";lamp.setAttribute("aria-label","OFF");b.prepend(lamp);const sync=()=>{const on=b.classList.contains("indicator-active");lamp.classList.toggle("on",on);lamp.classList.toggle("off",!on);lamp.setAttribute("aria-label",on?"ON":"OFF")};new MutationObserver(sync).observe(b,{attributes:true,attributeFilter:["class"]});sync()})}
function initIndicatorLights(){const styleId="mixer-indicator-lights";if(!document.getElementById(styleId)){const s=document.createElement("style");s.id=styleId;s.textContent=".lamp{display:inline-block;width:7px;height:7px;border-radius:50%;background:#263036;box-shadow:none;transition:background .08s,box-shadow .08s,opacity .08s}.lamp.active,.lamp.signal{background:#00e83f;box-shadow:0 0 6px #00e83f}.lamp.peak{background:#ffd400;box-shadow:0 0 7px #ffd400}.lamp.clip{background:#ef2027!important;box-shadow:0 0 8px #ef2027!important}.lamp.off{background:#263036;box-shadow:none;opacity:.45}.status-led{display:inline-block;width:7px!important;height:7px!important;border-radius:50%;background:#263036!important;box-shadow:none!important;transition:.08s}.status-led.signal{background:#00e83f!important;box-shadow:0 0 7px #00e83f!important}.status-led.peak{background:#ffd400!important;box-shadow:0 0 8px #ffd400!important}.status-led.clip{background:#ef2027!important;box-shadow:0 0 8px #ef2027!important}.status-led.off{background:#263036!important;box-shadow:none!important;opacity:.5}.ch-lamp{transition:height .06s,opacity .08s,filter .08s}.ch-lamp.signal{filter:brightness(1.25)}.ch-lamp.peak{filter:brightness(1.45)}.ch-lamp.clip{filter:brightness(1.7)}.input-meter.signal-active .power{color:#00ef42;text-shadow:0 0 6px #00ef42}.input-meter.clip-active .power{color:#ef2027;text-shadow:0 0 7px #ef2027}.master-strip .lamps{display:flex!important;flex-direction:column;gap:3px;line-height:1!important}.master-strip .lamps .lamp{width:8px;height:8px}.channel.signal-active{box-shadow:inset 0 0 0 1px #155c43}.channel.peak-active{box-shadow:inset 0 0 0 1px #806d00}.channel.muted .status-led{background:#ef2027!important;box-shadow:0 0 6px #ef2027!important}.channel.soloed .status-led{background:#ffd400!important;box-shadow:0 0 7px #ffd400!important}";document.head.appendChild(s)}document.querySelectorAll(".master-strip .lamps").forEach(box=>{if(!box.querySelector(".lamp"))box.innerHTML="<i class=\"lamp\"></i><i class=\"lamp\"></i><i class=\"lamp\"></i><i class=\"lamp\"></i><i class=\"lamp\"></i>"});document.querySelectorAll(".input-meter").forEach(box=>{if(!box.querySelector(".input-leds")){const x=document.createElement("div");x.className="input-leds";x.innerHTML="<span><i class=\"lamp\"></i>L</span><span><i class=\"lamp\"></i>R</span>";box.appendChild(x)}});document.querySelectorAll(".ch-head i").forEach(x=>x.classList.add("status-led"));document.querySelectorAll(".dca-grid button,.groups button").forEach(b=>{if(b.dataset.lightBound)return;b.dataset.lightBound="1";b.addEventListener("click",()=>b.classList.toggle("indicator-active"))});}
function bindMaifDcaUsbAudio(){const panel=document.querySelector(".dca");if(!panel)return;
const dcaMap=n=>{const start=(n-1)*4+1;return state.channels.filter(c=>{const ch=Number(c.dataset.channel);return ch>=start&&ch<start+4})};
panel.querySelectorAll(".dca-btn").forEach(b=>{b.addEventListener("click",()=>{const n=Number(b.dataset.dca),on=!state.dcaSolo.has(n);on?state.dcaSolo.add(n):state.dcaSolo.delete(n);b.classList.toggle("indicator-active",on);b.querySelector("span")&&(b.querySelector("span").textContent=on?"SOLO ON":"SOLO");dcaMap(n).forEach(c=>{c.classList.toggle("dca-soloed",on);});send("DCA "+n,"solo",on?1:0);updateDcaValues();})});
panel.querySelectorAll(".mute-groups button").forEach(b=>{b.addEventListener("click",()=>{const n=Number(b.dataset.group),on=!state.muteGroups.has(n);on?state.muteGroups.add(n):state.muteGroups.delete(n);b.classList.toggle("indicator-active",on);const start=(n-1)*4+1;state.channels.filter(c=>{const ch=Number(c.dataset.channel);return ch>=start&&ch<start+4}).forEach(c=>{c.classList.toggle("group-muted",on);c.classList.toggle("muted",on);updateChannelAudio(c)});send("MUTE GROUP "+n,"mute",on?1:0);updateMeters()})});
panel.querySelectorAll(".dca-groups button").forEach(b=>{b.addEventListener("click",()=>{const n=Number(b.dataset.dcagroup),on=!state.dcaGroups.has(n);on?state.dcaGroups.add(n):state.dcaGroups.delete(n);b.classList.toggle("indicator-active",on);send("DCA GROUP "+n,"active",on?1:0);status("DCA GROUP "+n+(on?" ON":" OFF"));})});
panel.querySelectorAll(".route-btn").forEach(b=>{b.addEventListener("click",()=>{panel.querySelectorAll(".route-btn").forEach(x=>x.classList.remove("indicator-active"));b.classList.add("indicator-active");state.activeRoute=b.dataset.route;send("ROUTING","route",b.dataset.route);status(b.dataset.route+" SELECTED")})});
panel.querySelectorAll(".usb-route-btn").forEach(b=>{b.addEventListener("click",()=>{const n=Number(b.dataset.usb);const ch=$("#musicChannel");if(ch){ch.value="CH "+n;ch.dispatchEvent(new Event("change",{bubbles:true}))}panel.querySelectorAll(".usb-route-btn").forEach(x=>x.classList.remove("indicator-active"));b.classList.add("indicator-active");send("USB "+n,"select",1);status("USB "+n+" SELECTED")})});
const auto=panel.querySelector(".auto-check");if(auto&&!auto.dataset.bound){auto.dataset.bound="1";auto.addEventListener("click",()=>{auto.classList.toggle("indicator-active");status("FADER MODE "+(auto.classList.contains("indicator-active")?"VERTICAL":"NORMAL"))})}
const detect=panel.querySelector("#detectUsbAudio");detect?.addEventListener("click",async()=>{if(locked||detect.dataset.busy==="1")return;detect.dataset.busy="1";try{if(state.usbStream?.active){state.usbStream.getTracks().forEach(t=>t.stop());state.usbStream=null;state.usbSource=null;state.usbDevice=null;setOn(detect,false);const st=panel.querySelector("#usbAudioStatus");if(st)st.textContent="● OFFLINE";const detail=panel.querySelector("#usbAudioDetail");if(detail)detail.textContent="USB audio input/output bridge • stopped";notify("USB AUDIO OFF",false);return}setOn(detect,false);notify("USB AUDIO DETECTING",false);const stream=await connectUsbAudio();const ok=!!stream?.active;if(!ok)throw Error("USB audio stream inactive");setOn(detect,true);const st=panel.querySelector("#usbAudioStatus");if(st)st.textContent="● ONLINE";const detail=panel.querySelector("#usbAudioDetail");if(detail)detail.textContent=(state.usbDevice||"USB Audio")+" • INPUT ACTIVE";notify("USB AUDIO ON • INPUT ACTIVE",true)}catch(e){setOn(detect,false);const st=panel.querySelector("#usbAudioStatus");if(st)st.textContent="● OFFLINE";notify("USB AUDIO OFF • "+(e.message||"UNAVAILABLE"),false)}finally{detect.dataset.busy="0"}});panel.querySelector(".usb-audio-box")?.addEventListener("click",e=>{if(e.target===e.currentTarget)panel.querySelector("#detectUsbAudio")?.click()});
panel.querySelectorAll(".usb-time").forEach(b=>b.textContent="00:00");
const audioBtn=$("#audioInputBtn");audioBtn?.addEventListener("click",()=>connectUsbAudio().catch(e=>status("AUDIO "+(e.message||"UNAVAILABLE"))));
const mic=$("#phoneMic");mic?.addEventListener("click",()=>connectUsbAudio().catch(e=>status("MIC "+(e.message||"UNAVAILABLE"))));
}
async function connectUsbAudio(){if(!navigator.mediaDevices?.getUserMedia)throw Error("Audio input tidak tersedia");if(state.usbStream?.active){status("USB AUDIO READY");return state.usbStream}const devices=await navigator.mediaDevices.enumerateDevices();const ins=devices.filter(d=>d.kind==="audioinput");if(!ins.length)throw Error("USB/MIC input tidak ditemukan");const preferred=ins.find(d=>/usb|audio interface|line in|mic/i.test(d.label))||ins[0];const stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:{exact:preferred.deviceId},echoCancellation:false,noiseSuppression:false,autoGainControl:false}});state.usbStream=stream;state.usbSource=null;if(state.ctx){state.usbSource=state.ctx.createMediaStreamSource(stream);if(!state.usbAnalyser){state.usbAnalyser=state.ctx.createAnalyser();state.usbAnalyser.fftSize=256;state.usbAnalyser.smoothingTimeConstant=.72}state.usbSource.connect(state.usbAnalyser);state.usbAnalyser.connect(state.masterGain);if(state.ctx.state==="suspended")await state.ctx.resume()}state.usbDevice=preferred.label||"USB Audio";status("USB AUDIO READY");const box=document.querySelector(".usb-audio-box span");if(box)box.textContent=state.usbDevice+" • INPUT ACTIVE";return stream}
function updateDcaValues(){document.querySelectorAll(".dca-btn").forEach(b=>{const n=Number(b.dataset.dca),chs=state.channels.filter(c=>{const x=Number(c.dataset.channel),s=(n-1)*4+1;return x>=s&&x<s+4}),avg=chs.length?chs.reduce((a,c)=>a+Number(c.querySelector(".fader")?.value||0),0)/chs.length:0,o=b.querySelector("output");if(o)o.value=(avg/100).toFixed(1)})}

function bindNativeButtons(){if(window.NativeMedia){$("#phoneRecorder")?.addEventListener("click",()=>NativeMedia.openRecorder());$("#phoneFiles")?.addEventListener("click",()=>NativeMedia.openFiles());$("#phoneMusic")?.addEventListener("click",()=>NativeMedia.openMusic())}}

// Boot only after the mixer state and all controls are initialized.
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
